bbr_additive: bbr_addtive.c
	gcc -Wall -o bbr_additive bbr_addtive.c
bbr_multi: bbr_multi.c
	gcc -Wall -o bbr_multi bbr_multi.c
ebest.: ebest.c
	gcc -Wall -o ebest ebest.c
parking_lot_sim.: parking_lot_sim.c
	gcc -Wall -o parking_lot_sim parking_lot_sim.c
